name: Publish
"on":
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - manifests/**
      - .release
jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v6
      - name: Install CUE
        uses: cue-lang/setup-cue@v1.0.1
      - id: get-version
        name: Compute next version based on previous tag in commit history
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: patch
      - name: Generate CUE OCI login creds
        run: |-
          mkdir -p ~/.docker
          echo '{"auths":{"ghcr.io":{"auth":"'$(echo -n "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" | base64)'"}}}' > ~/.docker/config.json
      - env:
          CUE_REGISTRY: github.com/${{ github.repository }}=ghcr.io/${{ github.repository_owner }},registry.cue.works
        run: cue mod publish "v${{ steps.get-version.outputs.nextStrict }}"
      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |-
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.get-version.outputs.nextStrict }}",
              sha: context.sha
            })
